Fix encoding error
    customStopwords = f.read().split(', ')
                      ^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'